### PR TITLE
footer icons added

### LINKED ISSUE #416: Feature Request- Add Respective Icons to Footer Section
**Is your feature request related to a problem? Please describe.**
Add respective icons to footer text 

**Describe the solution you'd like**
Add icons using react icons/bootstrap icons or font awesome icons to their respective texts in the footer section.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by robinokwanma**
**What kind of change does this PR introduce?**
Added icons to the footer section

**Issue Number:**

Fixes [#416](https://github.com/PalisadoesFoundation/talawa-docs/issues/416)

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

Here's how it was before
Screenshot (40)

Here is how it is after
Screenshot (39)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by robinokwanma** [comment]
@palisadoes please review. Cheers

**Comment by Cioppolo14** [comment]
@robinokwanma Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

**Comment by robinokwanma** [comment]
I'm Sorry, fixed that.

**Comment by Cioppolo14** [comment]
@robinokwanma Can you please make sure its all on the same line "Fixes #445".  Thank you!

**Comment by robinokwanma** [comment]
Done

**Review by Cioppolo14 — APPROVED** [review]

**Pull request merged**
