### PR TITLE
Relative links created, Page not found fixes, Reduntant links of YT removed, sidebar integrated with Plugins

### LINKED ISSUE #540: Bug Report: A. page not found fixes B. Redundant link fixes  C. adding "Functionalities page" to Sidebar
**Describe the bug**
Here, https://docs.talawa.io/docs/internships/internship-ideas/#api---primary-idea-areas

A. The Github Extenship links lead to "page not found" errors, and hence should be removed
image

B. The YouTube inspiration link 2 and 4 is the same
image

C. The Plugin guide redirects to a functionalities page, which isn't added to the Sidebar and hence is unreachable otherwise.
image
image

D. Apart from this, I also plan to make all the links relative, wherever possible.

**Expected behavior**
I wish to resolve this, by making the necessary changes.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Nitya-Pasrija**
**What kind of change does this PR introduce?**
I have implemented relative links and resolved issues with "Page not found" errors. Additionally, I have removed redundant links to YouTube and integrated the sidebar with the plugin docs. 

**Issue Number:**

Fixes #540 

**Snapshots/Videos:**
image
image
image

(https://docs.talawa.io/docs/internships/internship-ideas)

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Nitya-Pasrija** [comment]
@palisadoes @Cioppolo14

**Comment by Cioppolo14** [comment]
@Nitya-Pasrija Can you address the conflicting file?

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
I removed an extra YouTube link from the docs/internships/ideas.md file, from the Youtube Inspiration References

**Comment by Cioppolo14** [comment]
@Nitya-Pasrija You still have a conflict with the ideas.md file.  Can you fix that?

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
The conflict exists cuz I don't have permission to create changes in the ideas file, but they were required to delete the link..

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
The PR #560, is the corrected one, with the conflicts resolved. Closing this PR. Please review it.
Thanks

**Pull request closed without merging**
