### PR TITLE
Fixed  A. Navbar links in new tabs and B. Footer update

### PR DESCRIPTION
**Pull request by jmalicha**
**What kind of change does this PR introduce?**
Fixed headings for Talawa and Talawa API in the Navbar to open on a different page and changed the footer to Talawa from  my project

* Fixes issue: #507

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@jmalisha Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

**Comment by jmalicha** [comment]
@Cioppolo14  On it. Thanks

**Comment by jmalicha** [comment]
@Cioppolo14  I have tried reading the PR Guidelines but I still don't understand how to do that. Will you kindly explain this to me? Thanks

**Comment by jmalicha** [comment]
Hi @Cioppolo14 @Nitya-Pasrija The PR is ready for review

**Comment by Cioppolo14** [comment]
@jmalisha Thank you. Please make sure the issue number and the word Fixes are on the same line.  Something like "Fixes #512"

Please also fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done.

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
I was assigned this issue, and have worked on this one. Creating the PR part was left as I was in college and returned home just now. :(

**Comment by noman2002** [comment]
@jmalisha This issue is assigned to someone else. Please get an issue assigned in your name before submitting PR. All the best.

**Pull request closed without merging**
