### PR TITLE
Added workflow for pulling docs from api repo

### PR DESCRIPTION
**Pull request by adi790uu**
What kind of change does this PR introduce?

feature

Issue Number:

This PR is for the issue in api repo : https://github.com/PalisadoesFoundation/talawa-api/issues/1897

Did you add tests for your changes?

No

Snapshots/Videos:

If relevant, did you update the documentation?

No

Summary

This PR introduces a workflow which updated the talwa-api-repo folder to the latest changes.

Does this PR introduce a breaking change?

Yes

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by adi790uu** [comment]
@anwersayeed I don't know why the previous PR got closed but I have implemented the review comments.

**Comment by adi790uu** [comment]
@palisadoes we need to decide the schedule of cron job do give your opinion on this.

**Comment by palisadoes** [comment]
> @palisadoes we need to decide the schedule of cron job do give your opinion on this.

Please work with @anwersayeed and @tasneemkoushar on this and other questions. I trust their judgement.

**Comment by KinetiCore-Labs** [comment]
@adi790uu Set it to run weekly, every Sunday.

**Comment by adi790uu** [comment]
@anwersayeed changed it to sunday midnight

**Review by KinetiCore-Labs — APPROVED** [review]

**Comment by KinetiCore-Labs** [comment]
@palisadoes This PR is ready to be merged, once merged, we need to look for how it behaves on our repositories.

**Comment by KinetiCore-Labs** [comment]
@adi790uu Please work on replicating this for talawa-admin and talawa documentation as well.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
