### PR TITLE
 updated the documentation with a new figma file 

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**
updated the documentation with the new figma file

**Issue Number:**

Fixes #695

**Did you add tests for your changes?**
not required

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@palisadoes @noman2002 @tasneemkoushar please look into it and merge it.

**Comment by palisadoes** [comment]
@aashimawadhwa merge with the latest upstream. I think that will fix the errors

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa merge with the latest upstream. I think that will fix the errors

I am already up to date.

**Comment by palisadoes** [comment]
It's because of our upgrade to Docusaurus v3 and our Admin documentation workflow doesn't support the new markdown standard

1. Run this command in the root directory
    1. `npx docusaurus-mdx-checker`
1. Then add a `\` character in front of every `<`, `>`, `}` and `}` to every reported file. It's about 30 files. I'll send you a spreadsheet to make it faster
2. We have an issue to fix this.
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1279

**Pull request merged**
