### PR TITLE
fixed h1 an p to be responsive according to screen size.

### LINKED ISSUE #382: Feature Request
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
On the mobile friendly site the headings take up too many lines

**Describe the solution you'd like**
how about the font size be reduced just a little so that it can fit one or two lines
talawa2

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Promisemagoga**
https://user-images.githubusercontent.com/104593732/225212847-1aa820ba-03b2-4b01-9433-2929d292f546.mp4

 

**What kind of change does this PR introduce?**
The heading tag and the paragraph tag will adjust with respect to the device width.

**Issue Number:**
Fixes #382 

**Did you add tests for your changes?**
Yes I did test it on different screen size

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No it doesn't affect other components of this application.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Promisemagoga** [comment]
@palisadoes submitted a PR please review

**Comment by Cioppolo14** [comment]
@Promisemagoga Please address these 3 things: 
1) Please update your docusaurus version to the latest version. That way there will be no differences in the yarn.lock files. 

2) Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

3) Please also fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

Thank you!

**Comment by Promisemagoga** [comment]
@Cioppolo14  I did fix number 2 and number 3 as requested... But still having problems with number one, I did install docusaurus again so that it can be off the latest version and I pushed back my code, but it still  shows that conflict problems here... please advice

**Comment by Promisemagoga** [comment]
@Tajcore 
@Rumone
@kevoniat
I submitted a PR please review

**Comment by Cioppolo14** [comment]
@Promisemagoga My understanding is if you delete yarn.lock and have the latest version of docusaurus, it should have no conflicts or failed tests.  Does that help?

**Comment by Cioppolo14** [comment]
@Promisemagoga The merge conflict with  yarn.lock needs to be resolved.

**Review by Cioppolo14 — CHANGES_REQUESTED** [review]
Please update to the latest Docusaurus and delete the current yarn.lock file.

**Comment by Promisemagoga** [comment]
@Cioppolo14  working on it

**Comment by Promisemagoga** [comment]
@Cioppolo14  I did as you said. I belive the issue is resolved. Please review

**Comment by Cioppolo14** [comment]
@Promisemagoga Please resolve the conflicting files issue.  Yarn.lock should be the same as the one provided here: https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/yarn.lock

**Comment by Cioppolo14** [comment]
@Promisemagoga Could you please address the conflicting files? Yarn.lock has recently been updated.  I think this will finally fix it. Thank you!

**Comment by Promisemagoga** [comment]
@Cioppolo14  you said I should delete yarn.lock and update the docusaurus to the latest version, I did that. So how do I fix it now?

**Comment by Cioppolo14** [comment]
@Promisemagoga We just updated the yarn.lock in the repository. If you use the latest Docusaurus and the yarn.lock from the respository, there should show no file changes in yarn.lock in the PR. Does that help?

**Comment by Promisemagoga** [comment]
@Cioppolo14  fixed, please review

**Comment by Cioppolo14** [comment]
@Promisemagoga There are failing tests, can you look into this? It is okay to close this PR and start with a new one if that helps.

**Pull request closed without merging**
