### PR TITLE
Corrected a mistake of "you" with "your"

### PR DESCRIPTION
**Pull request by ALIRAZA17**
**What kind of change does this PR introduce?**

In the first line of the document there was a word you which should have been your.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by ALIRAZA17** [comment]
@palisadoes Can you review this?

**Comment by palisadoes** [comment]
There isn’t an issue assigned to you for this PR. Please follow the guidelines in our PR_GUIDELINES.md file. We have the procedures in place so that everyone has a fair chance of contributing. I will be closing this pull request. Please follow the procedures and resubmit when ready.

**Comment by ALIRAZA17** [comment]
> There isn’t an issue assigned to you for this PR. Please follow the guidelines in our PR_GUIDELINES.md file. We have the procedures in place so that everyone has a fair chance of contributing. I will be closing this pull request. Please follow the procedures and resubmit when ready.

@palisadoes How can I resubmit because the mistakes have been solved in the respective documents without my PR being merged?

**Comment by palisadoes** [comment]
Please follow the process and this will not happen.

**Pull request closed without merging**
