### PR TITLE
Docs : Plugin Architecture Overview Page

### LINKED ISSUE #251: Feature Request : Adding Plugin Architecture Overview Page
**Is your feature request related to a problem? Please describe.**
I would like to add the documentation to describe how plugin architecture is implemented and how we can convert existing features into plugins 

**Describe the solution you'd like**
I would like to add documentation for **detailed description** about the plugin architecture and **step by step process** to implement new features as plugins  
Expected Outcomes : 

- [x] Overview of What a plugin actually means in talawa repositories
- [x] A High-level diagram to describe workflow with description
- [x] Important code explanation

**Describe alternatives you've considered**
Alternatives can be suggested by mentors

### PR DESCRIPTION
**Pull request by SiddheshKukade**
**What kind of change does this PR introduce?**
Docs : Plugin Architecture Overview Page

**Issue Number:**

Fixes #251 

**Did you add tests for your changes?**
Not required

**Snapshots/Videos:**
Will be added soon

**If relevant, did you update the documentation?**
Yes 
**Summary**
Added 
 

- [x] Overview of What a plugin actually means in talawa repositories

- [x] A High-level diagram to describe workflow with description

- [x] code explanation

**Does this PR introduce a breaking change?**

No 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/master/CONTRIBUTING.md)?**

Yes

### OUTPUT : 
Output 1
output 2
output 3
output 4

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
I Would like to have Initial review from mentors for suggestions

**Comment by DMills27** [comment]
Looks good so far. You need to add more details in the different sections specifically the Talawa API section. Also, it's good you provided actual examples but you also should write about how someone could integrate their code as a plugin. For example, if we wanted to refactor the spam filter as a plugin what would be needed? What is the process of refactoring it?

**Comment by SiddheshKukade** [comment]
Thank you @DMills27 Sir for the review! Actually, I've created this page just for the **introduction** of the `Plugin Architecture` So that It would not be overwhelming for someone new. 
To explain the detailed Plugin creation process and Integrating Separate features as plugins and the example you have mentioned. I will create separate pages to describe them in depth. 
So that the docs would be more well structured.

What do you think about this approach?

**Comment by SiddheshKukade** [comment]
@DMills27 Sir, I've also updated the first comment with the screenshots and the pull request is now ready to be reviewed.
I've added this short video in the installation example to show the plugins in action. 

https://user-images.githubusercontent.com/65951872/201475372-028978ec-f2ae-44e0-86cb-dc034e0738da.mp4

Please suggest improvements, thanks 👍🏻

**Review by DMills27 — APPROVED** [review]
The new changes have provided easy to follow instructions and a clear overview. The video that you also added in the PR is not entirely clear at the moment but that can be fixed later on.

**Review by JamaicanFriedChicken — APPROVED** [review]

**Pull request merged**
