### PR TITLE
Update: Restructured the footer links

### LINKED ISSUE #418: Feature Request: Restructure the Footer links
**Describe the bug**
In the footer section, you can find the social media links, including the Contact Us link under the community section. This creates a UX writing flaw as the social media links should be listed under the Socials section while the Contact Us and Slack links could be listed under the Community section.
Screenshot from 2023-03-10 01-25-25

**My solution**
The Slack, News, and Contact Us including Opportunities links will be listed under the Community section. This is because they are speaking about the community, Talawa, and providing valuable resources. The social links; Facebook, Twitter, and Instagram will be listed under the Socials sections as they are social media platforms while GitHub and Team links will be listed under the Development section as they refer to the Development and Technical part of the community.

### PR DESCRIPTION
**Pull request by Vic-Orlands**
What kind of change does this PR introduce?
A feature change

Issue Number: https://github.com/PalisadoesFoundation/talawa-docs/issues/418

Fixes: https://github.com/PalisadoesFoundation/talawa-docs/issues/418

Snapshots/Videos:
This is the result of the final change made to the footer section.
Screenshot from 2023-03-11 04-46-37

Summary

In the footer section, you can find the social media links, including the Contact Us link under the community section. This creates a UX writing flaw as the social media links should be listed under the Socials section while the Contact Us and Slack links could be listed under the Community section.
See issue https://github.com/PalisadoesFoundation/talawa-docs/issues/418

My solution
The Slack, News, and Contact Us including Opportunities links will be listed under the Community section. This is because they are speaking about the community, Talawa, and providing valuable resources. The social links; Facebook, Twitter, and Instagram will be listed under the Socials sections as they are social media platforms while GitHub and Team links will be listed under the Development section as they refer to the Development and Technical part of the community.

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?
Yes, I read the contributing guide before contributing to this project.

### CODE REVIEW

**Comment by Vic-Orlands** [comment]
@Cioppolo14 I closed the other PR due to many commit conflicts and opened this instead.

**Review by Cioppolo14 — COMMENTED** [review]
Could you change any links that could be relative links, to relative links?

**Comment by Cioppolo14** [comment]
@Vic-Orlands The relative links are discussed in this comment/change section of this PR: https://github.com/PalisadoesFoundation/talawa-docs/pull/518   If the relative links break the links, then lets use the original. Could you try first and we'll see what happens?

**Comment by Vic-Orlands** [comment]
> @Vic-Orlands The relative links are discussed in this comment/change section of this PR: #518 If the relative links break the links, then lets use the original. Could you try first and we'll see what happens?

I have checked and there are no relative links on the navbar. PR #518 was not merged before mine as I was using the original links, so it didn't break my code.

**Review by Cioppolo14 — CHANGES_REQUESTED** [review]
@Vic-Orlands Please resolve the conflicting files, and we will be ready.

**Comment by Vic-Orlands** [comment]
> @Vic-Orlands Please resolve the conflicting files, and we will be ready.

@Cioppolo14  I have resolved the conflicts. Thank you.

**Review by Cioppolo14 — APPROVED** [review]

**Pull request merged**
