### PR TITLE
Changes in footer

### LINKED ISSUE #349: Feature Request : Improving footer
**Is your feature request related to a problem? Please describe.**
The footer can be arranged properly and new links can be added to it.
<br>
**Describe the solution you'd like**
Right now we only have slack link under **community section**. We can also add **twitter account** of Palisadoes Foundation, **Blog Link**, **Contact Us** under the community section.
Also instead of having a section named **"more"** we can use terms like **"Development"** and include GitHub link , reference to development team and opportunities under it.

**Screenshot** 
Screenshot 2023-03-07 202907

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by ayushi-8102**
**What kind of change does this PR introduce?**

Feature : Changes in footer

**Issue Number:**

Fixes #349 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

image

**Summary**
Changes in footer like adding twitter account , Contact us page  of Palisadoes Foundation, News (which is under news feed of talawa-docs) under community section.

Moreover, Changed "More" to "Development" and added new links like team(under members of talawa-docs) and Opportunities(Under Internships of talawa-docs).

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by ayushi-8102** [comment]
@Cioppolo14 please review the pull request and let me know if anything is wrong or improvement needed!

**Review by Cioppolo14 — CHANGES_REQUESTED** [review]
Could you delete the yarn.log file? For future PRs, just make sure you have the latest version.  The changes on the footer look good. Do you think it would be worth adding a link to our Facebook page, as well?

**Comment by ayushi-8102** [comment]
@Cioppolo14 Yeah sure I'll delete the yarn.lock file and will add facebook page as well under the community section!

**Comment by ayushi-8102** [comment]
@Cioppolo14 Hi! I just made the changes also I added the Instagram Link as well !

**ScreenShot :** 
image

**Comment by njorogedaniel** [comment]
Hello @ayushi-8102, I'd like to contribute to this feature

**Comment by ayushi-8102** [comment]
@njorogedaniel actually I'm working on it!

**Comment by ayushi-8102** [comment]
@Cioppolo14 I have created a new pull request kindly refer it!

**Pull request closed without merging**
