### PR TITLE
reduce height of navbar-sidebar

### LINKED ISSUE #414: Reduce the height of the drop down menu and make it scrollable
**Describe the bug**
The drop-down menu has only 4 elements and occupies the entire page.

**To Reproduce**

1. Switch to a smaller screen view
2. Open the drop-down menu

**Expected behavior**
Reduce the width of the drop-down menu and make it scrollable

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
talwa - Copy

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by tinniaru3005**
**What kind of change does this PR introduce?**
Reduce height of navbar-sidebar

**Issue Number:**

Fixes #414 

**Did you add tests for your changes?**

**Snapshots/Videos:**
WhatsApp Image 2023-03-10 at 3 46 13 PM

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Biki-das** [comment]
@tinniaru3005 does not seem appropriate , rather try to make it full width !

**Comment by tinniaru3005** [comment]
> @tinniaru3005 does not seem appropriate , rather try to make it full width !

Thanks a lot for taking the time to give feedback. But the issue was for reducing the height. Let's wait for someone to confirm and then if they approve it, I will make the changes.

**Review by Cioppolo14 — CHANGES_REQUESTED** [review]
I'm struggling with how this looks and wondering if it needs to be left as it is.  I've also looked at some other apps and it looks like it usually does stretch almost all the across and the full length down the screen.  Do you have any ideas or edits that might help?

**Comment by tinniaru3005** [comment]
> I'm struggling with how this looks and wondering if it needs to be left as it is. I've also looked at some other apps and it looks like it usually does stretch almost all the across and the full length down the screen. Do you have any ideas or edits that might help?

But currently there are only 3 elements in the drop down menu. So I don't think it's a good idea to span it across the entire page as there will be a lot of blank space left which is looking odd.

**Comment by tinniaru3005** [comment]
> I'm struggling with how this looks and wondering if it needs to be left as it is. I've also looked at some other apps and it looks like it usually does stretch almost all the across and the full length down the screen. Do you have any ideas or edits that might help?

layer5
Hey, this is the one I referred to. Let me know if it looks good to you. :)

**Comment by salman-farooqi** [comment]
> > I'm struggling with how this looks and wondering if it needs to be left as it is. I've also looked at some other apps and it looks like it usually does stretch almost all the across and the full length down the screen. Do you have any ideas or edits that might help?
> 
> layer5 Hey, this is the one I referred to. Let me know if it looks good to you. :)

1layer5
But their navbar is centralized (Thus, have full width and fully stretched all along the website), while Talawa's is floating to left, which makes the Talawa's navbar reasonable to stretch all along the website. **See in pic below...**
1talawa

**Comment by Cioppolo14** [comment]
@tinniaru3005 Yes I like the more recent example you sent.  Thank you. Can you show me what that would look like? I think something like this would work. Its hard to imagine it without seeing it. 

> > I'm struggling with how this looks and wondering if it needs to be left as it is. I've also looked at some other apps and it looks like it usually does stretch almost all the across and the full length down the screen. Do you have any ideas or edits that might help?
> 
> layer5 Hey, this is the one I referred to. Let me know if it looks good to you. :)

**Comment by tinniaru3005** [comment]
hey @Cioppolo14, Sure I will make the changes in a few hours and upload a screenshot in the comments. If that looks good to you I will go ahead and commit the changes.

**Comment by tinniaru3005** [comment]
WhatsApp Image 2023-03-18 at 7 01 32 PM
Hey @Cioppolo14, This is how it will look. I hope it helps you get an idea. Please let me know if more changes are required.

**Comment by Cioppolo14** [comment]
@tinniaru3005 I appreciate your work on this.  We have upcoming website changes and I'm not sure about this change right now.  I'm going to close the issue and PR.  I apologize for the change.

**Pull request closed without merging**
