### PR TITLE
flowchart images updated

### LINKED ISSUE #355: Workflow Diagram Almost Invisible in Darkmode Bug Report
**Describe the bug**
Under the GSOD 2022 and 2023 section, the workflow diagram is barely visible in darkmode

**To Reproduce**

1. Go to the Talawa documentation
2. Go to the Intership Section on the right side-bar
3. Click on GSOD drop down and select either the 2022 or 2023 option
4. make sure you have changed to darkmode

**Expected behavior**
A different image should be used with a different more visible color to ensure a good UX

**Actual behavior**
The same image is used for both light mode and darkmode and the colors are conflicting

**Screenshots**
Screenshot (30)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by robinokwanma**
**What kind of change does this PR introduce?**

bugfix. 
The flowchart image was not visible in dark mode and has been duly updated @Cioppolo14 

**Issue Number:**

Fixes #355

**Did you add tests for your changes?**

**Snapshots/Videos:**

Screenshot (31)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by Cioppolo14 — CHANGES_REQUESTED** [review]
Please delete yarn.lock, and in the future just make sure it is updated to the latest version.

**Comment by robinokwanma** [comment]
Hi @Cioppolo14  what's the update now?

**Comment by Cioppolo14** [comment]
@robinokwanma Did you add the css file after the first review? I don't remember seeing that there before. Does it change your screenshot sample?

**Comment by robinokwanma** [comment]
@Cioppolo14  No i just added a comment, i did not change or update any code in the css file.

**Review by Cioppolo14 — APPROVED** [review]

**Comment by palisadoes** [comment]
1. Please fix the failing tests. If we merge with the failure the site will go down.
1. Upgrade to the latest version of Docusaurus and then commit your changes.

**Comment by robinokwanma** [comment]
@palisadoes The docusaurus version is already up to date (2.3.1).

**Comment by palisadoes** [comment]
The deployment is failing because `yarn.lock` is missing. Please include it so the tests can pass.

**Comment by robinokwanma** [comment]
@palisadoes , I've done that and the deployment is successful, thank you for pointing that out.

**Pull request merged**
