### PR TITLE
feat: Update Docusaurus from v2 to v3

### LINKED ISSUE #685: Upgrade Talawa-Docs to Docusaurus v3.0
**Is your feature request related to a problem? Please describe.**
We need to upgrade to the latest version of docusaurus to take advantage of the latest features.

**Describe the solution you'd like**
You can do this by following the process outlined on the docusaurus site:

- https://docusaurus.io/docs/migration/v3

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- Follow the steps above

**Additional context**
- The functionality of the existing v2.x site must be maintained.
- Run the upgraded website on your local system to verify functionality

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #685 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

Update Docusaurus from v2 to v3

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by disha1202** [comment]
Hi @palisadoes,
Updated docusaurus from v2 to v3.
Please take a look.

**Comment by palisadoes** [comment]
These files must be excluded from the upgrade because:
1. They are autogenerated by pull requests in the other repos
2. They represent code blocks that should be left unchanged.

Please fix. 
1. Verify whether the `error-handling.md` file renders like we have on the site when finished.
2. Do the same with a representative sample of the other files. 

image

**Comment by palisadoes** [comment]
I just read the documentation and realized that the escaping of the characters in the 300+ files may be necessary.

Please verify whether the files rendered in your PR look the same as the rendering on the site. This is important to know with and without the mdx3 conversion so that we can alter our automated documentation workflows.

@tasneemkoushar, @anwersayeed FYI upgrading to Docusaurus v3 may cause issues with our workflows. This PR with the conversions seems to be escaping some javacript and HTML tags.

Details here:

- https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3

**Comment by palisadoes** [comment]
I'm getting this error when clicking through on some of the pages especially after switching tabs (Please fix and maintain the animation):

image

The pages themselves seem OK, but I'd like the others to test this too. Please do your own tests.

**Comment by palisadoes** [comment]
Please merge the latest `upstream/develop` branch with your branch. It has a fix for the links to the broken Talawa-Admin and Talawa-API documentation.

**Comment by disha1202** [comment]
> I'm getting this error when clicking through on some of the pages especially after switching tabs (Please fix and maintain the animation):
> 
> image
> 
> The pages themselves seem OK, but I'd like the others to test this too. Please do your own tests.

Sure, will look into it.

**Comment by disha1202** [comment]
I am unable replicate the error above, can you specify the exact steps and pages that lead to this error.

Also while testing I came across some formatting issues which are not there in V2.

Screenshot 2023-11-23 at 3 27 38 PM

Screenshot 2023-11-23 at 3 25 14 PM

I am working on fixing these right now.

**Comment by palisadoes** [comment]
The error occurs when I load the site in Opera

image

**Comment by palisadoes** [comment]
This error when loading in Firefox:

image

**Comment by palisadoes** [comment]
This error when loading in Chrome

image

**Comment by disha1202** [comment]
Thanks, I was able to reproduce the issue on my local. 
Also I believe this issue exists on [https://docs.talawa.io/](https://docs.talawa.io/) as well, as there is no element with the class [LogoAnimation](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/src/components/animations/_headerAnimation.js#L8)

**Comment by palisadoes** [comment]
Please take the necessary steps to rectify this

**Comment by tasneemkoushar** [comment]
@Nitya-Pasrija can you once check this PR, if the changes are breaking any of the workflow.

**Review by Nitya-Pasrija — CHANGES_REQUESTED** [review]
I am seeing major changes in the yarn.lock file. Please do not make any such changes here as it can break the application flow and do look into it that you have followed all the correct steps while cloning the repository.

**Comment by palisadoes** [comment]
> I am seeing major changes in the yarn.lock file. Please do not make any such changes here as it can break the application flow and do look into it that you have followed all the correct steps while cloning the repository.

@Nitya-Pasrija The docusaurus upgrade process requires extensive package updates to `package.json` which will automatically affect `yarn.lock`, correct?
- https://docusaurus.io/docs/migration/v3#upgrading-dependencies

It'll be important for you to review that page to see how the new `MDX` markdown format will affect the workflows you worked on earlier.

**Review by KinetiCore-Labs — APPROVED** [review]

**Comment by palisadoes** [comment]
We should merge this PR. It's been too long

@anwersayeed @tasneemkoushar how will the new version impact our automated workouts from dart docs, TS docs and graphql explorer

I want to make sure we don't have any additional documentation update issues because of this

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
