### PR TITLE
Admin files Configuration

### LINKED ISSUE #674: Integration of Talawa Admin TypeDoc generated files
**Describe the bug**
The files now being uploaded via the Talawa Admin TypeDoc workflow needs to be integrated. This issue necessitates proper linking and configuration of these files correctly.

**Describe the outcome**
Implementing the proposed pull request (PR) would ensure comprehensive uniformity in the Docusaurus design. Furthermore, it would automatically generate side navigation for the Admin files, enhancing the overall user experience.

### PR DESCRIPTION
**Pull request by Nitya-Pasrija**
**What kind of change does this PR introduce?**
The files now being uploaded via the Talawa Admin TypeDoc workflow are integrated with this PR. Proper linking and configuration of these files is completed.  This generates an automatic side nav and links the files together seamlessly.

**Issue Number:**
Fixes #674 

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
Yes, an introduction file for Talawa Admin was created.

**Summary**
Achieved design consistency and automation for documentation in the Admin section

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Nitya-Pasrija** [comment]
Note: 
Do NOT merge this PR until the pre-PR for documentation generation in Talawa Admin: Pull request (https://github.com/PalisadoesFoundation/talawa-admin/pull/960) is merged.

**Comment by Nitya-Pasrija** [comment]
@tasneemkoushar @noman2002 @palisadoes

**Comment by palisadoes** [comment]
Why is the deploy action failing?

**Comment by Nitya-Pasrija** [comment]
@palisadoes 
The workflow PR for the generation of Talawa Admin documentation hasn't been merged. Hence, the files will only be available when that is running.

**Comment by palisadoes** [comment]
What PR is that? Please ask your mentors to review it as a priority

**Comment by Nitya-Pasrija** [comment]
> Note: Do NOT merge this PR until the pre-PR for documentation generation in Talawa Admin: Pull request ([PalisadoesFoundation/talawa-admin#960](https://github.com/PalisadoesFoundation/talawa-admin/pull/960)) is merged.

This one

**Comment by palisadoes** [comment]
> > Note: Do NOT merge this PR until the pre-PR for documentation generation in Talawa Admin: Pull request ([PalisadoesFoundation/talawa-admin#960](https://github.com/PalisadoesFoundation/talawa-admin/pull/960)) is merged.
> 
> This one

Thanks. Please work with @tasneemkoushar and @anwersayeed to approve and merge that one.

**Comment by Nitya-Pasrija** [comment]
> > > Note: Do NOT merge this PR until the pre-PR for documentation generation in Talawa Admin: Pull request ([PalisadoesFoundation/talawa-admin#960](https://github.com/PalisadoesFoundation/talawa-admin/pull/960)) is merged.
> > 
> > 
> > This one
> 
> Thanks. Please work with @tasneemkoushar and @anwersayeed to approve and merge that one.

No worries, I will contact them.

**Review by tasneemkoushar — APPROVED** [review]

**Comment by palisadoes** [comment]
@Nitya-Pasrija The tests are also failing because the sidebar cannot be generated. Please review.

- https://github.com/PalisadoesFoundation/talawa-docs/actions/runs/5915989788/job/16042783961?pr=675

**Pull request merged**
