### PR TITLE
Add documentation for talawa_lint

### LINKED ISSUE #1641: Add a reference for our custom lint rules
**Is your feature request related to a problem? Please describe.**
We recently implemented custom lint rules but some contributors are facing difficulty in getting hold of what the rules expect.

**Describe the solution you'd like**
Add an example file in `talawa_lint` directory that will contain an exhaustive list of examples of our custom lint rules.

**Describe alternatives you've considered**
1. Add examples in CONTRIBUTING.md. But that will unnecessarily clutter this file.
2. Add examples in the official Talawa doc. I believe this can be done in conjunction with the original solution presented in this issue, so that the official doc serves as the official source of truth while the file in `talawa_lint` will come handy in referencing stuff quickly and locally.

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

Adds documentation for our newly added `talawa_lint` ecosystem.

**Issue Number:**

Fixes https://github.com/PalisadoesFoundation/talawa/issues/1641

**If relevant, did you update the documentation?**

Yes

### CODE REVIEW

**Comment by literalEval** [comment]
@palisadoes @Cioppolo14  please review and merge.

**Comment by palisadoes** [comment]
1. You need to update [sidebars.js](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/sidebars.js) to get the page added to the menu
2. Verify the changes with your own local instance of the docusaurus website running. Check INSTALLATION.md

**Comment by literalEval** [comment]
1. Yeah I was wondering why its not updating in the sidebar. Will update quickly.
2. Already done.

**Comment by literalEval** [comment]
@palisadoes done. Please review.

**Review by palisadoes — APPROVED** [review]

**Comment by literalEval** [comment]
@palisadoes please ask another reviewer to review and merge if possible. Thanks.

**Comment by jadeharr** [comment]
@literalEval Please make sure all your checks have been passed.

**Comment by literalEval** [comment]
@jadeharr I have modified 'sidebar.js` so all checks won't pass.

**Pull request merged**
