### PR TITLE
Migrate Talawa-API documentation to the Talawa-Docs Repo #65 

### PR DESCRIPTION
**Pull request by XshubhamX**
I have made inserted the Talawa Api documentation in talawa Docs. Please review @palisadoes air and @xsh2047 Sir.

### CODE REVIEW

**Comment by xsh2047** [comment]
@XshubhamX there seems to be a merge conflict, please review

**Review by xsh2047 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts in sidebars.js

**Comment by XshubhamX** [comment]
Sir i have resolved conflict in slidebar.js file. @xsh2047 Sir

**Review by xsh2047 — CHANGES_REQUESTED** [review]
For the overview page please fix the following typo:
"It is the base of all the functionalities offered to Users and Organizatios that sign up at talawa ."
(Organizatios should be organizations and the space at the end should be moved to the right of the full stop)

For the Authentication page:
Change the heading from "How a User can Authenticate?" to "How can a User Authenticate?"

For the Admin page:
"Administrators can remove any event, group chat or post belonging to the organization their responsible for."
(change their to they're)

For the Organization page:
"A user should create an account by signing up by their credentials. Steps for signing up are given on previous page."
(change signing up by their credentials to signing up with their credentials)
(Provide a link to the instructions. The previous page is too vague)

"Upon creating an account the use information would get stored in the databse. Now to create an Organization a request should be send to api having given fields."
(Database is not spelt correctly)
('Upon creating an account the use information' should be 'Upon creating an account the necessary information')

For the User page:
"He/She can create Group Chats, Events ,can make Posts that show up on the Organization, create Tasks for events and can Comment on posts."
(Make this into a list)

For the Expectations page:
"Allow a secure connection to both frontend interfaces ie: Admin console and Mobile application.using industry standard API authorization"
(Typo after fullstop)

"The current code base for talawa api uses Node.js, this poses several problems with scalability and stability."
(Comma should be fullstop and this should be capitalized)

"As the codebase is currently, adding new features in is unstable and prone to breaks."
(The sentence should continue from the first and 'in is unstable' should be 'making it unstable')

For the Functionality page:
"Following are the list of functionalities offered by Talawa Api"
(Start this heading with the)

For the description on the homepage below the banner, make them two sentences.

**Comment by XshubhamX** [comment]
@xsh2047  Sir I have resolved typos.

**Review by xsh2047 — APPROVED** [review]

**Pull request merged**
