### PR TITLE
fix h1 and p to be responsive according to screen size

### LINKED ISSUE #382: Feature Request
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
On the mobile friendly site the headings take up too many lines

**Describe the solution you'd like**
how about the font size be reduced just a little so that it can fit one or two lines
talawa2

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Promisemagoga**
**What kind of change does this PR introduce?**
The heading tag and the paragraph tag will adjust with respect to the device width.

**Issue Number:**

Fixes #382 

**Did you add tests for your changes?**
Yes I did test on different screen size.

**Snapshots/Videos:**

https://user-images.githubusercontent.com/104593732/226524299-21e31a85-a564-48f3-948c-eb9b06bfe666.mp4

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No it doesn't affect other components of the application.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Promisemagoga** [comment]
@Cioppolo14  opened a new PR as requested

**Comment by Biki-das** [comment]
hey @Promisemagoga seems like you have commited files not related to your commit! remove those and push again!

**Comment by Promisemagoga** [comment]
@Biki-das  I am lost,which file?🤔

**Comment by Promisemagoga** [comment]
@Biki-das can you please further explain that, I am lost as to what you are talking about and can you help by telling how do I remove them

**Comment by Biki-das** [comment]
@Promisemagoga 
you can do the below
```
git checkout HEAD^ -- /path/to/file

git commit -am "revert changes on this file, not finished with it yet"

git push

git checkout HEAD^ -- /path/to/file


```

**Comment by Promisemagoga** [comment]
@Biki-das I did as you said and the yarn.lock was uncommitted but the error is still not fixed...should I fork a new repo or ?

**Comment by Promisemagoga** [comment]
@Biki-das  Is it ok now?

**Comment by Promisemagoga** [comment]
@Cioppolo14  can you please review

**Comment by Promisemagoga** [comment]
@palisadoes please review

**Comment by Biki-das** [comment]
@Promisemagoga you have n't yet removed the appropriate files

**Comment by Promisemagoga** [comment]
@Biki-das I didn't?🤔how because there are no longer issues? I Did as you instructed... please clearify

**Pull request closed without merging**
