### PR TITLE
collapsible sidebar feature added

### LINKED ISSUE #227: Collapsible sidebar feature
The sidebar of the talawa-docs documentation website is currently not collapsible, if we have a collapsible sidebar, then it will allow users to better focus on the content.

### PR DESCRIPTION
**Pull request by anwersayeed**
Fixes #227
- **What kind of change does this PR introduce:** I have made the entire sidebar collapsible, allowing users to better focus on the content. This is especially useful when content is consumed on medium-sized screens (e.g. tablets).
- **Issue Number:** 227
- **Did you add tests for your code?** No
- **Snapshots/Videos:** image
- **Does this PR introduce a breaking change?** No
- **Other information:** This is especially useful when content is consumed on medium-sized screens (e.g. tablets).
- **Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?** Yes

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by anwersayeed** [comment]
https://github.com/PalisadoesFoundation/talawa-docs/issues/227
PR for this issue!

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please read the CONTRIBUTING.md file on how to auto-close issues when your PR is merged.
We have a PR template to assist you with this goal. You have deleted the template and therefore have made the cleanup of old issues more difficult.  Please update this PR for auto-closing

**Comment by anwersayeed** [comment]
> Please read the CONTRIBUTING.md file on how to auto-close issues when your PR is merged. We have a PR template to assist you with this goal. You have deleted the template and therefore have made the cleanup of old issues more difficult. Please update this PR for auto-closing

I have updated my PR after reading the CONTRIBUTING.md file, may I know if it is fine this time?

**Comment by palisadoes** [comment]
You need to put this in your comment, with no colons:

`Fixes #xyz`

**Comment by anwersayeed** [comment]
> You need to put this in your comment, with no colons:
> 
> `Fixes #xyz`



> You need to put this in your comment, with no colons:
> 
> `Fixes #xyz`

Done

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
