### PR TITLE
Changed the Background

### LINKED ISSUE #534: Bug Report: Update Background of Image to White
**Describe the bug**
The green background in the diagram/image is not ideal. Shown here: https://docs.talawa.io/docs/internships/gsod/gsod-ideas needs to be switched to white so it can be seen in both light and dark modes. 

**To Reproduce**
See image here: https://docs.talawa.io/docs/internships/gsod/gsod-ideas

**Expected behavior**
A clean image and color with no negative effects from light and dark mode changes. 

**Actual behavior**
The background color is not ideal, but can be seen in both light and dark modes. 

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Yogita-T**
Updated the background color to white while preserving the font style that was already used

**Issue Number:**

Fixes #534

### CODE REVIEW

**Comment by Yogita-T** [comment]
@Cioppolo14 I am not able to understand why I am failing the test. My docusaurus version is the same as it is supposed to be.

**Comment by Cioppolo14** [comment]
@Yogita-T Are you sure your new image's location matches the location that you put in the md files?

**Comment by Yogita-T** [comment]
> @Yogita-T Are you sure your new image's location matches the location that you put in the md files?

changes
Yes, it does. I tried running it on the local system and it just runs fine.

**Comment by Cioppolo14** [comment]
@Yogita-T Please make sure the name of the file exactly matches the markdown file, it is case sensitive.

**Comment by Yogita-T** [comment]
> > @Yogita-T Are you sure your new image's location matches the location that you put in the md files?
> 
> changes Yes, it does. I tried running it on the local system and it just runs fine.

I tried reviewing the yarn.lock file but there doesn't seem to be any sort of error.

**Comment by Yogita-T** [comment]
> 

I checked it. There seems to be no issue with that as well.

**Comment by Cioppolo14** [comment]
@Yogita-T Please match the case for "jpeg" in all locations, they should all either be jpeg or JPEG.  That should fix it.

**Comment by palisadoes** [comment]
Please rename the files to all lower case

**Comment by Yogita-T** [comment]
There was some issue with the `.jpeg` format. Changed the format to png and the issues seems to have resolved. Created a new PR 
#561

**Pull request closed without merging**
