### PR TITLE
Restructure the Footer links

### PR DESCRIPTION
**Pull request by Vic-Orlands**
**What kind of change does this PR introduce?**
A feature change

**Issue Number:** #418

**Snapshots/Videos:**
This is the result of the final change made to the footer section.
Screenshot from 2023-03-10 19-43-56

**Summary**

In the footer section, you can find the social media links, including the Contact Us link under the community section. This creates a UX writing flaw as the social media links should be listed under the Socials section while the Contact Us and Slack links could be listed under the Community section.
See issue  #418

My solution
The Slack, News, and Contact Us including Opportunities links will be listed under the Community section. This is because they are speaking about the community, Talawa, and providing valuable resources. The social links; Facebook, Twitter, and Instagram will be listed under the Socials sections as they are social media platforms while GitHub and Team links will be listed under the Development section as they refer to the Development and Technical part of the community.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**
Yes, I read the contributing guide before contributing to this project.

### CODE REVIEW

**Comment by Vic-Orlands** [comment]
@palisadoes Can you review my pull request and merge it? Thank you.

**Comment by Cioppolo14** [comment]
I am going to close this, as the files seem to cover more than just the identified issue.

**Comment by Vic-Orlands** [comment]
> I am going to close this, as the files seem to cover more than just the identified issue.

@Cioppolo14 I was assigned two different tasks. One to restructure the footer links and a bug to add installation.md file since it was not there. This is why there seems to be more than one issue covered

**Comment by Vic-Orlands** [comment]
See the issue numbers;  #419 and  #418

@Cioppolo14  @palisadoes

**Pull request closed without merging**
