### PR TITLE
fixed h1 and p tobe responsive for all screen size

### LINKED ISSUE #382: Feature Request
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
On the mobile friendly site the headings take up too many lines

**Describe the solution you'd like**
how about the font size be reduced just a little so that it can fit one or two lines
talawa2

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Promisemagoga**
**What kind of change does this PR introduce?**
The heading tag and the paragraph tag will adjust with respect to the device width

**Issue Number:**

Fixes #382 

**Did you add tests for your changes?**
yes I did test it on different screen size

**Snapshots/Videos:**

https://user-images.githubusercontent.com/104593732/226972123-8514ab17-b8f3-43b7-9018-06415cf7be00.mp4

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No it doesn't affect other components of the application.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Promisemagoga** [comment]
@Cioppolo14 
@palisadoes 

since I was having some issues, I started the process all over again and created a new PR, I hope this time I got it right, please review.

**Comment by Promisemagoga** [comment]
@Biki-das  please review

**Comment by Cioppolo14** [comment]
@Promisemagoga There is still a yarn.lock issue.

**Comment by Promisemagoga** [comment]
@Cioppolo14  I don't understand, all checks have passed,so what yarn issue?

**Comment by Cioppolo14** [comment]
@Promisemagoga If I merge this PR as it is right now, because there is a "yarn.lock" file in the "Files Changed" section, it will change the yarn.lock. We don't want to change the yarn.lock.

**Comment by Promisemagoga** [comment]
@Cioppolo14  so what do I do now? What's the solution?

**Comment by Promisemagoga** [comment]
@Cioppolo14  it is now fixed, the yarn.lock it is no longer in the files changed

**Review by Cioppolo14 — APPROVED** [review]

**Pull request merged**
