### PR TITLE
removed editUrl

### LINKED ISSUE #332: Invalid path for editing pages
**Describe the bug**
When we click on "Edit the page", the URL is broken and does not redirect to the correct file.

**To Reproduce**

1. Visit any page on the "About" tab of the documentation
2. Click on "Edit this page"

**Expected behavior**
Every page should have the corresponding correct URL for it's editing.

### PR DESCRIPTION
**Pull request by akankshat05**
**What kind of change does this PR introduce?**

Bugfix
**Issue Number:**

Fixes #332 

**Did you add tests for your changes?**
No

**Summary**

After this change, the "Edit this page" link on all pages will not be displayed.
**Does this PR introduce a breaking change?**

No
**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Biki-das** [comment]
this does not solve the issue , clicking on the link should direct to the github link making the change! rather removing it we have to make it dynamic such that it redirects to the corresponding doc section.

**Comment by Biki-das** [comment]
> this does not solve the issue , clicking on the link should direct to the github link making the change! rather removing it we have to make it dynamic such that it redirects to the corresponding doc section.

Looking forward to take this if you are not able to get a solution for the same :-)

**Review by palisadoes — APPROVED** [review]

**Comment by Biki-das** [comment]
@palisadoes this PR does not solve the issue! removing this is not the solution rather we need to make this redirect dynamically!
I have a better suggestion to keep the edit url option and then getting the docPath and passing it as parameter.

**Comment by palisadoes** [comment]
1. We don't want to edit the files directly. Only through PRs 
1. There is no content control or peer review otherwise

**Comment by Biki-das** [comment]
> 1. We don't want to edit the files directly. Only through PRs
> 
>     2. There is no content control or peer review otherwise

@palisadoes  got your point , but the redirect would actually present itself to go through a pull request , see below

https://user-images.githubusercontent.com/72331432/223780986-24de87b1-2076-4b4f-8b80-1ddf02e2cf36.mp4

**Pull request merged**
