### PR TITLE
Add automatic documentation of the API Schema [Fixes #629]

### LINKED ISSUE #629: Add Automatic Documentation of `Talawa API` GraphQL Schema
**Is your feature request related to a problem? Please describe.**
We want to use the [Graphql Markdown](https://graphql-markdown.github.io) package to automatically generate markdown documentation for the API's GraphQL schema and add it to the side. 

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by EshaanAgg**
**What kind of change does this PR introduce?**
Feature

**Issue Number:**

Fixes #629 

**Did you add tests for your changes?**
NA

**Snapshots/Videos:**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
Now the schema will be updated for the repository automatically whenever the `schema.json` file is changed from the Talawa API's github action. 

**Does this PR introduce a breaking change?**
No

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
The documentation files are there, but there is no way to access them from the webserver menu

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. The documentation files are there, but there is no way to access them from the webserver menu.
2. The `sidebars.js` file was not updated. The tab spacings were changed, but no new menu items seem to have been added. 

Without the updates to `sidebars.js`, this valuable new content will not be visible on the site.

**Comment by EshaanAgg** [comment]
1. Can you elaborate on this webserver thing? Locally, I can access them.
image
Clicking schema documentation tab opens the generated pages.
image

2. I had updated the `sidebars.js` to include a new sidebar.
image

**Comment by palisadoes** [comment]
1. I was expecting it to be added to the sidebar under docs. 
1. It's not an intuitive location where it is now.
1. The docs links from the other repos will need to eventually be moved from the nav bar too. The reason for this is that every new integration will be on the NavBar and we'll run out of space. 
1. It is not intuitive either. For example, we now have two links in the NavBar for the API. One for the modules and another for the schema.

How can this be content be added under the existing sidebar? There must be a way to do this.

**Comment by EshaanAgg** [comment]
I'm not sure how can we do the same. Currently, all the sidebars and their values are added manually to the file `sidebars.js`. But the whole point of using the plugin so that we do not have to generate anything ourselves. Even in the documentation of the plugin, there is no section about integrating it with already existing sidebar (except for the import that I have already done)

I'll read about it a bit more never the less.

**Comment by palisadoes** [comment]
> I'm not sure how can we do the same. Currently, all the sidebars and their values are added manually to the file `sidebars.js`. But the whole point of using the plugin so that we do not have to generate anything ourselves. Even in the documentation of the plugin, there is no section about integrating it with already existing sidebar (except for the import that I have already done)
> 
> I'll read about it a bit more never the less.

There must be a way where we can:
1. add a single manual entry into the sidebar which then links to `docs/schema`. We already have an entry for schemas here which could be replaced: 
    1. http://localhost:3000/docs/developers/talawa-api/schemas 
1. remove the current NavBar entry

That way we have a more logical flow.

I have noticed that the automated schema content is not as good as the manually created one which has more context.

1. Automated: http://localhost:3000/docs/schema/queries/posts
2. Manual: http://localhost:3000/docs/developers/talawa-api/schemas

Additional questions:
1. Is there a way where the schema.json file can include comments from the original source code for things like the arguments and queries?
1. How can we get all the links to work in the new automated schema? For example in the case above for http://localhost:3000/docs/schema/queries/posts, you get 404 errors when you click on:
    1. [PostOrderByInput](http://localhost:3000/schema/enums/post-order-by-input)
    2. [Post](http://localhost:3000/schema/objects/post)

**Comment by EshaanAgg** [comment]
Got it @palisadoes. I would try to work on all of the questions and suggestions you have posted above, and come up with an answer ASAP.

**Comment by EshaanAgg** [comment]
@palisadoes As you can see in this PR, the `test-deploy` job is working correctly, as the same doesn't have the latest changes pulled from the `talawa automatic documentation updation`. Thus we can safely say that it's not the recently added `Talawa API` job that is causing the deployment to fail here in the docs. 

You may consider closing [this issue](https://github.com/PalisadoesFoundation/talawa-api/issues/1298) as the same in not the cause of the problem as far as I can understand.

**Comment by EshaanAgg** [comment]
@palisadoes 
1. I have added an entry for the same in the sidebar in the API section, and removed it from the main navbar. 
2. The schema.json file already has the descriptions for some fields that has comments describing their purpose in the typeDefs in `Talawa-API`. You can make it as a project for potential `GSoD` candidates to add comments to the typeDefs describing the use of each type. Then the same would be automatically reflected in the documentation here. 
3. I have fixed the links which were not working earlier. 
4. The automated content would never be as good as the manually created content for obvious reasons. But I guess it's a tradeoff that we have to make, as we want all of out code to be documented and not such some parts of it.

**Comment by EshaanAgg** [comment]
@palisadoes Can you please review the PR as is? I would fix the conflicts later after your approval, as as soon as I pull changes from the `develop` branch, even the `test-deploy` job would start to fail for this PR due to the introduction of improperly named files in the recent merges.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicts

**Comment by EshaanAgg** [comment]
@palisadoes Done.

**Comment by palisadoes** [comment]
@EshaanAgg @literalEval How can we fix the GitHub Pages deployment error?

**Comment by literalEval** [comment]
@palisadoes I researched a bit about it and the some ideas refer to adding some sort of numbering or hash to the file name, so that they can never be same as each other. But `Dart Doc` doesn't not seem to support this. I have raised an issue regarding this on their repo though.

A temporary fix, as I said before, can be to rename the field from `message` to `messageStr` maybe will generate files with different names.

**Comment by palisadoes** [comment]
1. Rename it if required and create a PR. 
2. Make sure it doesn't break the code elsewhere.

**Comment by EshaanAgg** [comment]
@literalEval Wouldn't renaming things require all the hyperlinks to the same automated as well? Does `Dart Doc` support the same?

**Comment by literalEval** [comment]
@EshaanAgg that's exactly what I am discussing with the `DartDoc` maintainers.

**Comment by EshaanAgg** [comment]
@palisadoes Please review.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicts

**Comment by palisadoes** [comment]
@EshaanAgg The push run failed. Please troubleshoot this
- https://github.com/PalisadoesFoundation/talawa-docs/actions/runs/4710652445

**Comment by EshaanAgg** [comment]
@palisadoes Opened a fixing PR #639

**Pull request merged**
