### PR TITLE
feat(fix): link of the desired features page.

### LINKED ISSUE #636: Bug Report: Desired features link doesn't work on ideas page
**Describe the bug**

Currently, the desired features link in the ideas page is redirecting an old URL:  https://docs.talawa.io/docs/internships/features/features-introduction

**To Reproduce**
Steps to reproduce the behaviour:

1.  Go to https://docs.talawa.io/docs/internships/gsoc/gsoc-ideas
2. Click on desired features 
3. Link leads to 404 error
4.

**Expected behaviour**
Corrected link is 

**Actual behaviour**
A clear and concise description of how the code performed w.r.t expectations.
Should redirect here: https://docs.talawa.io/docs/features/features-introduction/
**Screenshots**
image
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by SiddheshKukade**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #636

**Did you add tests for your changes?**
Yes
**Snapshots/Videos:**
N/A

**If relevant, did you update the documentation?**
Yes

**Summary**
Fixed the link path

**Does this PR introduce a breaking change?**
No 
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
@Cioppolo14, the link will work fine now 👍🏻

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
We need to figure out how to fix the failing tests.

**Comment by SiddheshKukade** [comment]
@palisadoes, can I take a look to fix that ?

**Comment by palisadoes** [comment]
You can work with @literalEval on a solution. When that is resolved we can then merge this PR

- https://github.com/PalisadoesFoundation/talawa-docs/pull/632#issuecomment-1508966988

**Comment by palisadoes** [comment]
@SiddheshKukade Please merge with the latest upstream and update this PR. The error should be rectified.

**Comment by Cioppolo14** [comment]
@SiddheshKukade Is there any update on this?

**Comment by SiddheshKukade** [comment]
@Cioppolo14, the code is ready to be merged.

**Comment by SiddheshKukade** [comment]
The CI/CD checks are also passing now 👍🏻

**Pull request merged**
