### PR TITLE
[GSOC]Docs : Adding Step by Step Plugin Example with Code explanation

### LINKED ISSUE #255: Docs : Adding Step by Step Plugin Example with Code explanation
### This Issue is associated with Google Summer of Code 2022 Project  [link](https://summerofcode.withgoogle.com/programs/2022/projects/zjlx9dIj)

**Is your feature request related to a problem? Please describe.**
Adding Step by Step Plugin Example with Code explanation
Recently Plugin Architecture is implemented in talawa repositories with Plugin store on the admin. A detailed step by step example must be created to showcase the process of conversion of existing feature as a plugin.

**Describe the solution you'd like**

- [x] Technical overview of the steps used to convert the features into pluigns #256 
- [x] Step-by-step example of actual conversion of a feature to a plugin (ex. Donation feature) #258 

**Describe alternatives you've considered**

**Approach to be followed (optional)**
Add the docs by explaining the plugin architecture example

### PR DESCRIPTION
**Pull request by SiddheshKukade**
### This Pull Request is associated with Google Summer of Code 2022 Project  [link](https://summerofcode.withgoogle.com/programs/2022/projects/zjlx9dIj)

 

**What kind of change does this PR introduce?**
Documetation

**Issue Number:**

Fixes #255
**Did you add tests for your changes?**
Not needed

**Snapshots/Videos:**
## Preview of the `Technical Overview` Page.

image
image
image
image
image
image
image
image

**If relevant, did you update the documentation?**

Yes 
**Summary**
Added the Docs : Adding Step by Step Plugin Example with Code explanation
 
## This is part 1 of the issue #255  and this page contains Code explanations of the steps required to implement plugins

 

**Does this PR introduce a breaking change?**
No

**Other information**
Not required

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Review by DMills27 — APPROVED** [review]
LGTM

**Comment by SiddheshKukade** [comment]
@palisadoes sir please check this Pull request

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@SiddheshKukade Please fix the conflicting files so that we can merge.

**Comment by SiddheshKukade** [comment]
@palisadoes sir the merge conflicts are now fixed

**Pull request merged**
