### PR TITLE
Added FAQ section to talawa-docs

### PR DESCRIPTION
**Pull request by nangahamandine**
Added FAQ section to Talawa docs which provides answers to the frequently asked questions that users might have
- Created a new module 'faq.md' for part of the documentation for some questions and answers
- Updated the 'sidebars.js' file with the appropriate routing for the 'faq' section
- 
Issue 
FAQ section missing from docs website  #340

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@nangahamandine Can you reword the answers to the questions a bit? We'd like the responses to appear to a more casual user, like the leaders of the organizations who will eventually be using it. As an example, the first question about the Talawa Project could be focused on why someone might want to use it.  Then another question could ask "How did the Talawa Project get started?" (which could be answered with the paragraph that begins with "Talawa is based on the original 'Quito' code...").   Another example would be to rephrase the second question and answer for that casual user. Something like, "What can a leader of a non-profit do with Talawa?" And answered with something like, "A leader of a non-profit can set up their organization within Talawa. This will allow them to do things like plan events, coordinate volunteers, and post updates."    These are examples to help explain what I mean by rephrasing the questions and answers to help explain to a casual user/non-profit lead.

**Review by Cioppolo14 — CHANGES_REQUESTED** [review]
Can you reword the answers to the questions a bit? We'd like the responses to appear to a more casual user, like the leaders of the organizations who will eventually be using it. As an example, the first question about the Talawa Project could be focused on why someone might want to use it. Then another question could ask "How did the Talawa Project get started?" (which could be answered with the paragraph that begins with "Talawa is based on the original 'Quito' code..."). Another example would be to rephrase the second question and answer for that casual user. Something like, "What can a leader of a non-profit do with Talawa?" And answered with something like, "A leader of a non-profit can set up their organization within Talawa. This will allow them to do things like plan events, coordinate volunteers, and post updates." These are examples to help explain what I mean by rephrasing the questions and answers to help explain to a casual user/non-profit lead.

**Comment by nangahamandine** [comment]
> Can you reword the answers to the questions a bit? We'd like the responses to appear to a more casual user, like the leaders of the organizations who will eventually be using it. As an example, the first question about the Talawa Project could be focused on why someone might want to use it. Then another question could ask "How did the Talawa Project get started?" (which could be answered with the paragraph that begins with "Talawa is based on the original 'Quito' code..."). Another example would be to rephrase the second question and answer for that casual user. Something like, "What can a leader of a non-profit do with Talawa?" And answered with something like, "A leader of a non-profit can set up their organization within Talawa. This will allow them to do things like plan events, coordinate volunteers, and post updates." These are examples to help explain what I mean by rephrasing the questions and answers to help explain to a casual user/non-profit lead.

Okay, thanks for the corrections
I'll make the necessary changes

**Comment by Cioppolo14** [comment]
@nangahamandine  Please use what I said and make it your own.  Look at all the questions & answers and see if they can be adjusted to communicate towards an average user who may not know coding.  Thank you!

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Please fix the conflicting files.
1. The FAQ menu item should reside under the [About Us menu item](https://docs.talawa.io/docs/).
1.  The FAQ link in the header should redirect to the the FAQ location.

**Pull request closed without merging**
