### PR TITLE
workflow and script for admin docs

### PR DESCRIPTION
**Pull request by adi790uu**
What kind of change does this PR introduce?

feature

Issue Number:

This PR is for the issue in api repo : https://github.com/PalisadoesFoundation/talawa-api/issues/1897

Did you add tests for your changes?

No

Snapshots/Videos:

If relevant, did you update the documentation?

No

Summary

This PR introduces a workflow which updates the talawa-admin-docs folder to the latest changes.

Does this PR introduce a breaking change?

Yes

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@anwersayeed @tasneemkoushar Can you review this PR?

**Comment by Cioppolo14** [comment]
@adi790uu Should the Deploy to github pages be skipped ?

**Comment by adi790uu** [comment]
@Cioppolo14 I think yeah it can be skipped

**Comment by KinetiCore-Labs** [comment]
@adi790uu Is it ready to merge? We already merged a similar PR for talawa-api.
We can merge it to a separate branch to test the changes it brings. We can then merge it develop.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
