### PR TITLE
Update: Restructured the footer links

### LINKED ISSUE #418: Feature Request: Restructure the Footer links
**Describe the bug**
In the footer section, you can find the social media links, including the Contact Us link under the community section. This creates a UX writing flaw as the social media links should be listed under the Socials section while the Contact Us and Slack links could be listed under the Community section.
Screenshot from 2023-03-10 01-25-25

**My solution**
The Slack, News, and Contact Us including Opportunities links will be listed under the Community section. This is because they are speaking about the community, Talawa, and providing valuable resources. The social links; Facebook, Twitter, and Instagram will be listed under the Socials sections as they are social media platforms while GitHub and Team links will be listed under the Development section as they refer to the Development and Technical part of the community.

### PR DESCRIPTION
**Pull request by Vic-Orlands**
What kind of change does this PR introduce?
A feature change

Issue Number: https://github.com/PalisadoesFoundation/talawa-docs/issues/418

Fixes: https://github.com/PalisadoesFoundation/talawa-docs/issues/418

Snapshots/Videos:
This is the result of the final change made to the footer section.
Screenshot from 2023-03-11 04-46-37

Summary

In the footer section, you can find the social media links, including the Contact Us link under the community section. This creates a UX writing flaw as the social media links should be listed under the Socials section while the Contact Us and Slack links could be listed under the Community section.
See issue https://github.com/PalisadoesFoundation/talawa-docs/issues/418

My solution
The Slack, News, and Contact Us including Opportunities links will be listed under the Community section. This is because they are speaking about the community, Talawa, and providing valuable resources. The social links; Facebook, Twitter, and Instagram will be listed under the Socials sections as they are social media platforms while GitHub and Team links will be listed under the Development section as they refer to the Development and Technical part of the community.

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?
Yes, I read the contributing guide before contributing to this project.

### CODE REVIEW

**Comment by Vic-Orlands** [comment]
@palisadoes  @Cioppolo14 Can you review and merge it? Thank you.

**Comment by Cioppolo14** [comment]
@Vic-Orlands Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

**Comment by Vic-Orlands** [comment]
> @Vic-Orlands Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

I have fixed it.

**Review by Cioppolo14 — CHANGES_REQUESTED** [review]
Please update to the latest version of Docusaurus, so that the yarn.lock file is not needed in the PR.

**Comment by Vic-Orlands** [comment]
@Cioppolo14 

> Please update to the latest version of Docusaurus, so that the yarn.lock file is not needed in the PR.

I have updated the Docusaurus to the latest version and removed yarn.lock file

**Comment by Cioppolo14** [comment]
@Vic-Orlands Could you please resolve the conflicting files.?  Yarn.lock has recently been updated. Thank you!

**Pull request closed without merging**
