### PR TITLE
Fix page break and header texts

### PR DESCRIPTION
**Pull request by Ugboaja-Uchechi**
**What kind of change does this PR introduce?**

A bugfix

**Issue Number:**

Fixes issue #485 

**Snapshots/Videos:**

Before | After
------------- | -------------
image  |  image

**Summary**

- In this PR I fixed the page break in the "plugin-architecture" page.
- I also adjusted the `font-size` of the `h2` and `h3` tags because of how similar they looked so as to make a clear hierarchy of different headers to make it easier for users to differentiate different headings.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Ugboaja-Uchechi 
Please fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done.

Also, please ensure that Docusaurus is updated to the latest version, and delete the yarn.lock file.

**Comment by Ugboaja-Uchechi** [comment]
@Cioppolo14 
Thank you for the review.  I've worked on them and I'm ready for another review.

**Comment by Cioppolo14** [comment]
@Ugboaja-Uchechi Please resolve the failing tests.  Updating your Docusaurus to the latest version, so that there are no yarn.lock differences may help with this.

**Comment by Ugboaja-Uchechi** [comment]
Hi @Cioppolo14. I've tried updating Docusaurus to the latest version. If this is still the version that isn't suitable can you push me in the right direction of the version required?

**Comment by Cioppolo14** [comment]
@Ugboaja-Uchechi Thanks for your effort! Lets try this. The yarn.lock file should not be listed in the "Files Changed" list.  I think using this file will resolve that:  https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/yarn.lock.  Can you try that and let's see how it goes.

**Comment by Ugboaja-Uchechi** [comment]
Hi @Cioppolo14. Thank you for the guidance. Is it better now?

**Review by Cioppolo14 — CHANGES_REQUESTED** [review]
@Ugboaja-Uchechi There is still one difference between the yarn.lock files.  Can you try one more time using the yarn.lock file provided in my comments before? We are so close!

**Comment by Ugboaja-Uchechi** [comment]
Hi @Cioppolo14. I just updated it again.

**Comment by Cioppolo14** [comment]
Could you please address the conflicting files? Yarn.lock has recently been updated.  Thank you!

**Comment by Cioppolo14** [comment]
@Ugboaja-Uchechi Could you please address the conflicting files? Yarn.lock has recently been updated. Hopefully this makes it so there is no differences in the yarn.lock file.  We shouldn't have a yarn.lock files under "Files Changed" Thank you!

**Comment by Ugboaja-Uchechi** [comment]
@Cioppolo14. I've updated the yarn.lock file.

**Comment by Cioppolo14** [comment]
@Ugboaja-Uchechi There is still yarn.lock differences. I think it might be best to close this PR, make a new one, and ensure you have the latest Docusaurus and yarn.lock file before making the PR.  I hope that resolves it!

**Pull request closed without merging**
