### PR TITLE
Multiple user guide

### LINKED ISSUE #686: Improve Layout + Groundwork for Setting Up Multiple User Guides
Our docs.talawa.io website has a major deficiency in that it focuses only on our developer community. It does not provide any documentation for either administrators or end users. It would also be useful to have a blog.

We want to make the following changes.

Maintain the current home page with updated links, namely:

1. User Guide – Directing to docs.talawa.io/users
    1. This must direct to a “User guide coming soon” page. We will add the rest of the pages later.
    1. This section must have its own completely separate left hand side menuing system.
    1. The documentation for this section must be located under the talawa-docs/users directory or some other unique name that minimizes confusion with other document trees.
1. Admin Guide - Directing to docs.talawa.io/admins
    1. This must direct to a “Admin guide coming soon” page. We will add the rest of the pages later.
    1. This section must have its own completely separate left hand side menuing system.
    1. The documentation for this section must be located under the talawa-docs/admins directory or some other unique name that minimizes confusion with other document trees.
1. Developer Guide - Directing to our existing docs.talawa.io/docs URI
    1. The current left hand side menuing system must be maintained
    1. The documentation for this section must be located under the existing talawa-docs/docs directory
    1. All CI/CD integrations with other repos must not break. These integrations must operate and update the correct document trees when updated. For ease of implementation you may consider using the existing directory structure for these integrations.
1. Blog - Directing to docs.talawa.io/blog
    1. Consider using the default blog plugin: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog 

We have done some research and discovered that it is possible to have multiple document URIs in a single docusaurus instance:

- https://stackoverflow.com/questions/60783595/is-there-a-way-to-have-two-docs-in-docusaurus-2 

Please work with @tasneemkoushar and @anwersayeed who have worked extensively with our CI/CD integrations. Ask to be assigned this task by them.

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**
feature

**Issue Number:**

Fixes #686 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-docs/assets/58461801/ab1b7f07-0533-4330-9533-4ea36eada9ed

**If relevant, did you update the documentation?**

**Summary**

Added multiple user guides for users and admins
**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@disha1202 Thanks for the work on this. This is a good first step, and a long overdue improvement. I have some minor comments:

1. Please prove that the left hand menu for the User and Admin guides are visible. So instead of having the coming-soon.md files have a introduction.md and getting-started.md file both with a "coming soon" message. This will be useful to show that the functionality exists and will also be a guide that others could use to add more pages.
1. Also, please rearrange the order menu bar items to be User guide, Admin guide and Developer Guides. Add "Docs" to the Developer Guides dropdown menu and rename it "General" and add it to the top. This will hopefully make the expected flow more intuitive.

We don't usually accept draft PRs, and close them immediately due to past experiences. I'll make an exception here, but keep this in mind in future.

**Comment by disha1202** [comment]
@palisadoes Thank you for considering this PR. I'll keep this mind for future PRs.

**Comment by disha1202** [comment]
1. Improved sidebar for user and admin guides
2. Rearranged menu bar items

**Comment by disha1202** [comment]
https://github.com/PalisadoesFoundation/talawa-docs/assets/58461801/99373e89-4986-47a3-a3f2-6d6d76e8acff

**Comment by palisadoes** [comment]
@disha1202 This looks much better.

1. Why are so many of the files edited with escape characters? Is this because you are using Docusaurus v3?
2. We need this to be done against the existing Docusaurus version. v3 should be separate.

Please revert to v2 for this PR and let us know when ready.

**Comment by disha1202** [comment]
@palisadoes 

Updated the PR so that its compatible with docusaurus V2.

Please take a look.

**Comment by palisadoes** [comment]
Now that I think about it, we actually have two user guides. One for mobile and the other for web. 
1. How would you add that while maintaining the overall design and keeping it clean and intuitive?
2. If this is not possible with the existing design, what changes would you propose to make?

**Comment by disha1202** [comment]
> Now that I think about it, we actually have two user guides. One for mobile and the other for web.
> 
> 1. How would you add that while maintaining the overall design and keeping it clean and intuitive?
> 2. If this is not possible with the existing design, what changes would you propose to make?

I can think of two possible approaches based on the existing flow

1. We can have web and mobile categories inside the user documentation
2. We can have separate documentation for web and mobile and provide links in a dropdown menu, similar to how developer docs are structured.

What do you think?

**Comment by palisadoes** [comment]
1. Option 2 is better
2. How would you handle this button?

image

**Comment by palisadoes** [comment]
@disha1202 Any updates? We will soon need to update other docs and I'd like to have this feature implemented in the next couple of days. It will be very helpful.

**Comment by disha1202** [comment]
@palisadoes I'll make sure complete it in the next couple of days. 

Also, regarding the users button, perhaps we can have general documentation that is applicable to both web and mobile users. If not, do you have anything else in mind?

**Comment by palisadoes** [comment]
We'll need documentation for:

1. Web Users
2. Mobile Users
3. Admin Users
4. Developers

To save space in the buttons you can just have:

1. Mobile
2. Web
3. Admins
4. Devs

The directory format can remain (docs-*) and the existing menu bar items would then be:

1. Mobile Guide
2. Web Guide
3. Admin Guide
4. Developer Guide

Thanks. We are preparing for January and this will help a lot.

**Comment by disha1202** [comment]
Implemented separate docs for web and mobile users

**Comment by disha1202** [comment]
https://github.com/PalisadoesFoundation/talawa-docs/assets/58461801/df99287e-eb58-43c7-b1ab-8d944ca48917

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Thanks @disha1202

**Pull request merged**
