### PR TITLE
Refactor:- Talawa homepage refactor

### LINKED ISSUE #635: Refactor/Update : Homepage Section for Improved Developer Experience and Clean Code
**Describe the bug**

The current code for our new website is not as clean, developer-friendly, and professional as it could be. This issue aims to address these concerns by refactoring and updating the homepage, ultimately making it easier for developers to contribute to the project.

**Additional details**
Not Required

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Biki-das**
**What kind of change does this PR introduce?**

refactor

**Issue Number:**

fixes partially #635

**Did you add tests for your changes?**

 No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

@aviraldevv raised this issue of refactoring the code of the Talawa current documentation home landing, the whole of code was injected into one file and it need organization with tweaks here and there, to make it easy for future maintenance , code readability and easy to apply changes.

I have organized the file into layouts and then added them to the main `index.ts` file , also since the files were not regular react component ,they were typescript components, so i have also introduced type safety to few components wherever possible, there was a small change in one of the animation file , which is done to introduce better performance.

**Does this PR introduce a breaking change?**

No

**Other information**

I was instructed by @aviraldevv to push the PR of my changes, see comment #https://github.com/PalisadoesFoundation/talawa-docs/issues/635#issuecomment-1524049598

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Biki-das** [comment]
cc @Cioppolo14 @aviraldevv , i have made the PR to have a better understanding of my changes, if you feel to close it, it's fine!

**Comment by palisadoes** [comment]
@anwersayeed @tasneemkoushar  @evasharma12 @Kevoniat @Rumone Please review

**Comment by aviraldevv** [comment]
@Biki-das 

Please share the screen-recording of running website with current changes.

**Review by aviraldevv — COMMENTED** [review]
In the layout section just keep the panels. Rest all components can be moved to utils .

Also panel should be renamed as -

- HeaderHero
- SecondPanel
- ThirdPanel
 .
 .
 .
- EigthPanel

**Comment by Biki-das** [comment]
> @Biki-das 
> 
> Please share the screen-recording of running website with current changes.

Sure!

**Comment by aviraldevv** [comment]
@Biki-das 

I would like to suggest some more changes to the PR -

- Delete the contents of `component` folder we don't need it. It was part of our old website .
- Move the `layout` and `animations` folder to component folder.
- Try to re-arrange the `index.css` file in same manner as that of panels.

Also please fix the comment of your PR so that it doesn't automatically closes the parent issue.

**Comment by Biki-das** [comment]
> @Biki-das
> 
> @aviraldevv  Please share the screen-recording of running website with current changes.


https://user-images.githubusercontent.com/72331432/235347566-059d1dbd-3542-406f-9b11-29ca73d580ff.mp4

**Comment by aviraldevv** [comment]
Looks good, go ahead with the rest of the changes.

**Comment by Biki-das** [comment]
@aviraldevv pushed the changes as requested by you ,regarding the PR fix tag which issue should i link to you as you said it will either close the parent issue!

**Comment by aviraldevv** [comment]
> @aviraldevv pushed the changes as requested by you ,regarding the PR fix tag which issue should i link to you as you said it will either close the parent issue!

Just make it -

Fixes
#**Issue Number**

This will not automatically close the issue.

**Comment by aviraldevv** [comment]
@Biki-das 

Is the website functional after changes??

**Comment by Biki-das** [comment]
> @Biki-das 
> 
> Is the website functional after changes??

Yep it's working fine also checked for responsiveness too and everything seem to work

**Review by Kevoniat — APPROVED** [review]

**Review by aviraldevv — APPROVED** [review]

**Comment by aviraldevv** [comment]
> > @aviraldevv pushed the changes as requested by you ,regarding the PR fix tag which issue should i link to you as you said it will either close the parent issue!
> 
> Just make it -
> 
> Fixes #**Issue Number**
> 
> This will not automatically close the issue.

@Biki-das 

Please do this before it gets merged.

**Comment by Cioppolo14** [comment]
@Biki-das Please fix the first comment...maybe we can mention the issue without closing it, so that it is trackable in the future?   Am I understanding it correctly that we don't want to close https://github.com/PalisadoesFoundation/talawa-docs/issues/635 because @aviraldevv is still working on it? This just supports that effort in part?

**Comment by Biki-das** [comment]
> @Biki-das Please fix the first comment...maybe we can mention the issue without closing it, so that it is trackable in the future? Am I understanding it correctly that we don't want to close #635 because @aviraldevv is still working on it? This just supports that effort in part?

yes! @aviraldevv told to keep it fix#issuenumber,
@Cioppolo14 done, i have just made a mention type making the f smallercase, this won't close the issue now!

**Comment by aviraldevv** [comment]
@Cioppolo14 

We can merge this now.

**Pull request merged**
