### PR TITLE
Grammatical errors Corrections

### PR DESCRIPTION
**Pull request by MohitGupta14**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by MohitGupta14** [comment]
Correcting Grammar errors in the about section of introduction of the page.

**Comment by salman-farooqi** [comment]
You didn't provide the issue number, or maybe you didn't even opened the issue, so I think it won't be accepted as by the guidelines https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/PR_GUIDELINES.md

**Comment by Cioppolo14** [comment]
@MohitGupta14 There isn’t an issue assigned to you for this PR. Please follow the guidelines in our PR_GUIDELINES.md file. We have the procedures in place so that everyone has a fair chance of contributing. I will be closing this pull request. Please follow the procedures and resubmit when ready.

**Comment by MohitGupta14** [comment]
Sorry for the trouble I am very new to open-source and having a hard time figuring out everything here. I request the Mentor to guide me and assign me an issue. I read the documentation and did the initial setup on my computer. I am into the MERN stack field and want to contribute to this repo.

**Pull request closed without merging**
