### PR TITLE
Added changes

### LINKED ISSUE #448: Feature Request: Add a Section to About Us Describing Technologies Used
**Is your feature request related to a problem? Please describe.**
There is a lot of important, missing data in our About Us page. 

**Describe the solution you'd like**
Add a section in "about us" describing the technologies used in Talawa, and listing the important pages to read for a introduction the technical side of Talawa. This will require some research, our youtube channel will be a helpful resource: https://www.youtube.com/@PalisadoesOrganization/videos. 

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
See above.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Yogita-T**
Added a section called `technologies used` to the About Us page on the Talawa Docs. Added the repository links to various projects under the Foundation. Also, added a list of various technologies in different parts of the implementation of the Application.

**Issue Number:**

Fixes #448

### CODE REVIEW

**Comment by Yogita-T** [comment]
@palisadoes @Cioppolo14  Please review the changes. Thank you!

**Comment by Cioppolo14** [comment]
@Yogita-T Please fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done.

**Comment by Yogita-T** [comment]
> @Yogita-T Please fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done.

Updated the comment!  Could you please review it?

**Comment by Yogita-T** [comment]
> > @Yogita-T Please fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done.
> 
> Updated the comment! Could you please review it?

Review pending!

**Comment by Yogita-T** [comment]
@Cioppolo14  @palisadoes  Please review. Thank you!

**Review by Cioppolo14 — APPROVED** [review]

**Pull request merged**
