### PR TITLE
Changed the architecture diagram

### LINKED ISSUE #447: Feature Request: Recreate/Update Image, and Replace Architecture Image
**Is your feature request related to a problem? Please describe.**
The image representing the Architecture of Talawa on the Applications page needs to be recreated and modernized. 

**Describe the solution you'd like**
The above mentioned image needs to be recreated with a modern look, but effectively communicate the design. 

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
N/A

**Additional context**
When asking to be assigned this issue, provide a sample of what you'd like to do with it. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Yogita-T**
**Issue Number:**

Fixes #447

### CODE REVIEW

**Comment by palisadoes** [comment]
Thanks. Please remove the border around the image so that it will look less constrained when it's on the web page. We should be OK after that.

**Comment by Yogita-T** [comment]
> Thanks. Please remove the border around the image so that it will look less constrained when it's on the web page. We should be OK after that.

Do you mean the border around the boxes or the whole image?

**Comment by palisadoes** [comment]
> > Thanks. Please remove the border around the image so that it will look less constrained when it's on the web page. We should be OK after that.
> 
> Do you mean the border around the boxes or the whole image?

The whole image

**Comment by Yogita-T** [comment]
Could you please review the changes?

**Review by Cioppolo14 — CHANGES_REQUESTED** [review]
Please remove the green border around the entire image. 
Could you also provide a screen shot on how it will look in replacement on the page, since they are different sizes?  Thank you!

**Comment by Yogita-T** [comment]
> Please remove the green border around the entire image. Could you also provide a screen shot on how it will look in replacement on the page, since they are different sizes? Thank you!

There is no green border around the image. When you review the changes, the green border is just in the preview. Here is the screenshot:

imagearch

**Comment by Cioppolo14** [comment]
> > Please remove the green border around the entire image. Could you also provide a screen shot on how it will look in replacement on the page, since they are different sizes? Thank you!
> 
> There is no green border around the image. When you review the changes, the green border is just in the preview. Here is the screenshot:
> 
> imagearch

Thank you! Sorry I didn't register the "new" green border.

**Review by Cioppolo14 — APPROVED** [review]

**Pull request merged**
