### PR TITLE
Feat: Implement automated updates with Dependabot (#694)

### LINKED ISSUE #694: Configure Automated Dependabot Updates
We need to make sure our code is constantly up to date especially for our `develop` branch. To do this we need to implement automated updates using dependabot. This has already been done with the Talawa repo, but we also need it done for this one.

Requirements

1. Weekly updates
1. Run against the `default` branch
1. Use the appropriate package system
1. Use the appropriate root directory

Other information

1. Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
1. Talawa Example: https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/dependabot.yaml

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Harsh1s**
Configure automated Dependabot updates to keep the codebase current on the develop branch. This aligns with Talawa's setup, running weekly updates against the default branch, using the correct package system and root directory.

Closes #694

 

**What kind of change does this PR introduce?**

- [ ] Bug Fix
- [ ] Feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Documentation Update

**Issue Number:**

Fixes #694

**Did you add tests for your changes?**

- [ ] Yes
- [x] No

**Snapshots/Videos:**

N/A

**If relevant, did you update the documentation?**

N/A

**Summary**

Configure automated Dependabot updates to keep the codebase current on the develop branch. This aligns with Talawa's setup, running weekly updates against the default branch, using the correct package system and root directory.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Other information**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

- [x] Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please take a look at Docusaurus' configuration file to see what we may require. We don't want the `github-actions` section as this is not a very highly active repo
- https://github.com/facebook/docusaurus/blob/main/.github/dependabot.yml

**Comment by Harsh1s** [comment]
> Please take a look at Docusaurus' configuration file to see what we may require. We don't want the `github-actions` section as this is not a very highly active repo
> 
> * https://github.com/facebook/docusaurus/blob/main/.github/dependabot.yml

I went through this file and needed your help understanding the requirements. The only actual difference is that I have not used the `open-pull-requests-limit: 0` part. But from my understanding, that is used to disable the version updates for npm dependencies. So is this true for this dependency too? Does it need disabling the version updates for npm dependencies?

**Comment by EshaanAgg** [comment]
IMO we should also update the `npm` dependencies until they do not break the build; otherwise, we are setting up ourselves for a technical backlog in the future.

**Comment by palisadoes** [comment]
Yes we have had this outdated dependency difficulty in the past. They should be updated. That is why we decided to restore the dependabot workflow

**Comment by Harsh1s** [comment]
> Yes we have had this outdated dependency difficulty in the past. They should be updated. That is why we decided to restore the dependabot workflow

So I guess my original PR should work, I'll redo it without the `open-pull-requests-limit: 0` argument.

**Review by EshaanAgg — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
