### PR TITLE
Feature/documentation

### PR DESCRIPTION
**Pull request by bonnie-23**
added messaging and installation feature requirements doc

### CODE REVIEW

**Comment by jordanliu** [comment]
Resolve conflicts @bonnie-23

**Comment by bonnie-23** [comment]
@jordanliu I reorganized docs

**Comment by jordanliu** [comment]
@bonnie-23, could you unstage/remove the .idea folder?

**Comment by bonnie-23** [comment]
> @bonnie-23, could you unstage/remove the .idea folder?

done.

**Review by jordanliu — APPROVED** [review]

**Pull request merged**
