### PR TITLE
add doc for updated remove user funtion

### LINKED ISSUE #308: Documenting the new remove member mutation in the scema
**Describe the bug**

**To Reproduce**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #308

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@kb-0311 Please fix the conflicting files so that this can be merged

**Comment by palisadoes** [comment]
@kb-0311 Please fix the conflicting files so that this can be merged

**Comment by Cioppolo14** [comment]
@kb-0311 Please fix the conflicting files.

**Comment by kb-0311** [comment]
Ohh I completely forgot about this PR, the editor is saying that the changes are too complex to do it in web editor, gonna close this one and open another one to do the same thing after pulling the latest develop branch.

**Pull request closed without merging**
