### PR TITLE
Changed the architecture image

### LINKED ISSUE #447: Feature Request: Recreate/Update Image, and Replace Architecture Image
**Is your feature request related to a problem? Please describe.**
The image representing the Architecture of Talawa on the Applications page needs to be recreated and modernized. 

**Describe the solution you'd like**
The above mentioned image needs to be recreated with a modern look, but effectively communicate the design. 

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
N/A

**Additional context**
When asking to be assigned this issue, provide a sample of what you'd like to do with it. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Yogita-T**
Changed the architecture diagram that outlines how the three Talawa components interact.

**What kind of change does this PR introduce?**

The image goes well with the overall UI.

**Issue Number:**
Fixes https://github.com/PalisadoesFoundation/talawa-docs/issues/447

**Snapshots/Videos:**
architecture1

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Yogita-T Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

**Comment by Yogita-T** [comment]
> @Yogita-T Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

I am not able to understand what you mean. Could you help? 
Thank you!

**Comment by palisadoes** [comment]
Please make the three service layer boxes into horizontal title text to the left. All text left aligned. The differently oriented boxes and tight margins make it hard to read.

**Comment by Cioppolo14** [comment]
@Yogita-T In order for the issue to be closed automatically when the PR is merged, the Issue Number item should say "Fixes #447".  Please also address the comment from palisadoes. Finally, please update your docusaurus version so it matches Talawa Docs.  This should mean there are no yarn.lock differences.   Thank you!

**Comment by Yogita-T** [comment]
Could you review the changes?

**Review by Cioppolo14 — CHANGES_REQUESTED** [review]
Thank you for updating this. I have the following questions:
1) Is there another type of box you could use for the layers? Something that stands out but isn't quite as bulky. 
2) Could you add an "s" at the end of administrator.
3) Can you remove yarn.lock? Please make sure it Docusaurus is updated.

**Comment by Yogita-T** [comment]
> Thank you for updating this. I have the following questions:
> 
> 1. Is there another type of box you could use for the layers? Something that stands out but isn't quite as bulky.
> 2. Could you add an "s" at the end of administrator.
> 3. Can you remove yarn.lock? Please make sure it Docusaurus is updated.

Alright, Thank you for the review.

**Comment by Yogita-T** [comment]
Could you please review the changes? Thank you

**Comment by noman2002** [comment]
@Yogita-T Please fix the failing test.

**Comment by palisadoes** [comment]
Thanks. Here are some suggestions:

1. The mobile App will only be used by members
2. The Admin portal will only be used by administrators
3. Please remove the boxes around the descriptions of the layer
4. Move the descriptions of the layers further left so that they are in their own separate space without text or images interfering in it. At the moment it is cluttered.
5. Please use Talawa green for the boxes https://docs.talawa.io/docs/design/branding
6. The lines around the boxes are too thick. Please use the minimum width line available in the package. 
7. Make the lines around the boxes light grey so that they don't compete with the words.

**Comment by Yogita-T** [comment]
Closing this pull request create a new one.

**Pull request closed without merging**
